export enum LogNamespace {
  DETAILS_SERVICE_NAMESPACE = 'DETAILS-SERVICE',
  ADAPTER_CONTEXT_MIDDLEWARE_NAMESPACE = 'ADAPTER-CONTEXT-MIDDLEWARE',
  HEALTH_NAMESPACE = 'health',
  API_ADAPTER_REQUEST_NAMESPACE = 'API-ADAPTER-SERVICE',
  HTTP_UTILS_NAMESPACE = 'HTTP-UTILS',
  APP_NAMESPACE = 'APP',
  SERVER_NAMESPACE = 'SERVER',
  ERROR_HANDLER_NAMESPACE = 'ERROR-HANDLER',
  REQUEST_LOGGER_NAMESPACE = 'REQUEST-LOGGER-MIDDLEWARE',
  ADMIN_CONTROLLER_NAMESPACE = 'ADMIN-CONTROLLER',
  VISITOR_CONTROLLER_NAMESPACE = 'VISITOR-CONTROLLER',
  AUTH_CONTROLLER_NAMESPACE = 'AUTH-CONTROLLER',
  DASHBOARD_CONTROLLER_NAMESPACE = 'DASHBOARD-CONTROLLER',
  AUTH_SERVICE_NAMESPACE = 'AUTH-SERVICE',
  COMMON_SERVICE_NAMESPACE = 'COMMON-SERVICE',
  DEFAULT = 'default'
}
